---
kind: pipeline
name: user-ubuntu-14.04
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - echo "Pulled latest template files:"
  - ls -1 docker-user-image
  - ./generate_manifest.sh user-ubuntu amd64 arm32v7 arm64v8
  - echo "Generated docker manifest template:"
  - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 14.04-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:14.04

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 14.04-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:14.04

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 14.04-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:14.04

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 14.04
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-ubuntu-16.04
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - echo "Pulled latest template files:"
  - ls -1 docker-user-image
  - ./generate_manifest.sh user-ubuntu amd64 arm32v7 arm64v8
  - echo "Generated docker manifest template:"
  - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 16.04-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:16.04

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 16.04-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:16.04

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 16.04-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:16.04

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 16.04
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-ubuntu-18.04
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - echo "Pulled latest template files:"
  - ls -1 docker-user-image
  - ./generate_manifest.sh user-ubuntu amd64 arm32v7 arm64v8
  - echo "Generated docker manifest template:"
  - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 18.04-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:18.04

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 18.04-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:18.04

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 18.04-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:18.04

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 18.04
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

---
kind: pipeline
name: user-ubuntu-latest
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - echo "Pulled latest template files:"
  - ls -1 docker-user-image
  - ./generate_manifest.sh user-ubuntu amd64 arm32v7 arm64v8
  - echo "Generated docker manifest template:"
  - cat .manifest.tmpl

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: latest-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:latest

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: latest-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:latest

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: latest-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:latest

- name: docker-push-manifest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

