---
kind: pipeline
name: prepare
trigger:
  branch:
  - master
  event:
  - push
clone:
  disable: true

steps:
- name: register-qemu
  image: multiarch/qemu-user-static:register
  command: [ "--reset" ]
  privileged: true

---
kind: pipeline
name: user-ubuntu-14.04
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-ubuntu arm64v8 arm32v7 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl
  volumes:
    - name: cache
      path: /cache

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    create_repository: true
    use_cache: true
    tags:
      - trusty-arm64v8
      - 14.04-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:14.04
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    create_repository: true
    use_cache: true
    tags:
      - trusty-arm32v7
      - 14.04-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:14.04
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    create_repository: true
    use_cache: true
    tags:
      - trusty-amd64
      - 14.04-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:14.04
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest-trusty
  image: plugins/manifest:1
  environment:
    DRONE_TAG: trusty
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-14.04
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 14.04
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - prepare

---
kind: pipeline
name: user-ubuntu-16.04
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-ubuntu arm64v8 arm32v7 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl
  volumes:
    - name: cache
      path: /cache

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    create_repository: true
    use_cache: true
    tags:
      - xenial-arm64v8
      - 16.04-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:16.04
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    create_repository: true
    use_cache: true
    tags:
      - xenial-arm32v7
      - 16.04-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:16.04
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    create_repository: true
    use_cache: true
    tags:
      - xenial-amd64
      - 16.04-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:16.04
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest-xenial
  image: plugins/manifest:1
  environment:
    DRONE_TAG: xenial
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-16.04
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 16.04
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - prepare

---
kind: pipeline
name: user-ubuntu-18.04
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: prepare
  image: docker:git
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
    - echo "Enabled build caching"
    - git submodule update --init --recursive
    - echo "Pulled latest template files:"
    - ls -1 docker-user-image
    - ./generate_manifest.sh user-ubuntu arm64v8 arm32v7 amd64
    - echo "Generated docker manifest template:"
    - cat .manifest.tmpl
  volumes:
    - name: cache
      path: /cache

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    create_repository: true
    use_cache: true
    tags:
      - bionic-arm64v8
      - 18.04-arm64v8
      - latest-arm64v8
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:18.04
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    create_repository: true
    use_cache: true
    tags:
      - bionic-arm32v7
      - 18.04-arm32v7
      - latest-arm32v7
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:18.04
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    create_repository: true
    use_cache: true
    tags:
      - bionic-amd64
      - 18.04-amd64
      - latest-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:18.04
  volumes:
    - name: docker
      path: /var/lib/docker

- name: docker-push-manifest-bionic
  image: plugins/manifest:1
  environment:
    DRONE_TAG: bionic
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-18.04
  image: plugins/manifest:1
  environment:
    DRONE_TAG: 18.04
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

- name: docker-push-manifest-latest
  image: plugins/manifest:1
  environment:
    DRONE_TAG: latest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: .manifest.tmpl

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker

depends_on:
  - prepare

---
kind: pipeline
name: notify
trigger:
  branch:
  - master
  event:
  - push
  status:
  - success
  - failure
clone:
  disable: true

steps:
- name: send-notification
  image: appleboy/drone-discord
  allow_failure: true
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_token
    message: >
      {{#success build.status}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch succeeded!
      {{else}}
        **{{repo.name}}**: Build #{{build.number}} on {{build.branch}} branch failed. Fix me please. {{build.link}}
      {{/success}}

depends_on:
  - user-ubuntu-14.04
  - user-ubuntu-16.04
  - user-ubuntu-18.04

