---
kind: pipeline
name: user-ubuntu-14.04
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 14.04-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:14.04

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 14.04-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:14.04

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 14.04-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:14.04

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-ubuntu:14.04
    template: phasecorex/user-ubuntu:14.04-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

---
kind: pipeline
name: user-ubuntu-16.04
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 16.04-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:16.04

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 16.04-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:16.04

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 16.04-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:16.04

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-ubuntu:16.04
    template: phasecorex/user-ubuntu:16.04-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

---
kind: pipeline
name: user-ubuntu-18.04
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 18.04-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:18.04

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 18.04-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:18.04

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: 18.04-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:18.04

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-ubuntu:18.04
    template: phasecorex/user-ubuntu:18.04-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

---
kind: pipeline
name: user-ubuntu-rolling
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: rolling-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:rolling

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: rolling-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:rolling

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: rolling-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:rolling

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-ubuntu:rolling
    template: phasecorex/user-ubuntu:rolling-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

---
kind: pipeline
name: user-ubuntu-latest
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: latest-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/ubuntu:latest

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: latest-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/ubuntu:latest

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-ubuntu
    tags: latest-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/ubuntu:latest

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-ubuntu:latest
    template: phasecorex/user-ubuntu:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

